[project]
name = "telegram-shop-remnawave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.21.0",
    "python-dotenv>=1.1.1",
    "remnawave>=2.0.0",
    "sqlalchemy>=2.0.42",
    "telegram>=0.0.1",
]
